HOTELS = [
    # ========== MUMBAI (8) ==========
    {
        "name": "JW Marriott Mumbai Juhu",
        "brand": "JW Marriott",
        "city": "Mumbai",
        "latitude": 19.0926,
        "longitude": 72.8307,
        "description": "Iconic beachfront luxury hotel on Juhu Beach with panoramic Arabian Sea views.",
        "semantic_text": "Luxurious JW Marriott beachfront resort on Juhu Beach, Mumbai. Stunning Arabian Sea sunset views, world-class spa, outdoor lagoon pool, and award-winning seafood restaurant. Ideal for romantic getaways, luxury family vacations, and high-end business events. Lush tropical gardens create a serene, peaceful atmosphere away from Mumbai's bustle.",
        "rating": 4.7,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "beach_access": True},
        "price_per_night": 22000,
        "hotel_type": "luxury",
    },
    {
        "name": "The St. Regis Mumbai",
        "brand": "The Ritz-Carlton",
        "city": "Mumbai",
        "latitude": 18.9971,
        "longitude": 72.8360,
        "description": "Exquisite luxury in Lower Parel, occupying floors 12-37 of the iconic Palladium tower.",
        "semantic_text": "Ultra-luxury St. Regis experience in Mumbai's most prestigious commercial district. Panoramic city skyline views, butler service, world-class spa sanctuary, and Michelin-starred dining. Perfect for luxury business travelers, discerning couples, and celebrations. Refined sophisticated ambiance with impeccable attention to detail and privacy.",
        "rating": 4.8,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "butler_service": True},
        "price_per_night": 28000,
        "hotel_type": "luxury",
    },
    {
        "name": "Marriott Marquis Mumbai",
        "brand": "Marriott Marquis",
        "city": "Mumbai",
        "latitude": 19.0708,
        "longitude": 72.8680,
        "description": "Majestic business-class hotel near Mumbai airport with extensive meeting facilities.",
        "semantic_text": "Grand business hotel near Mumbai International Airport with excellent connectivity to corporate hubs. Expansive conference facilities, high-speed wifi throughout, executive lounge access, and 24-hour business center. Perfect for corporate travelers, business delegations, and large conferences. Efficient professional atmosphere with Marriott's signature warm hospitality.",
        "rating": 4.5,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "business_center": True},
        "price_per_night": 16000,
        "hotel_type": "business",
    },
    {
        "name": "Renaissance Mumbai Convention Centre Hotel",
        "brand": "Renaissance",
        "city": "Mumbai",
        "latitude": 19.1276,
        "longitude": 72.8663,
        "description": "Sprawling convention hotel overlooking Powai Lake with serene waterfront views.",
        "semantic_text": "Spacious convention hotel perched on the hillside overlooking beautiful Powai Lake, Mumbai. Peaceful lakeside setting with lush greenery, infinity pool with lake views, rejuvenating spa treatments, and vibrant dining options. Excellent for conferences, workcations, and family weekend getaways. Tranquil retreat-like atmosphere despite being in the heart of India's busiest city.",
        "rating": 4.4,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "convention_center": True},
        "price_per_night": 14000,
        "hotel_type": "business",
    },
    {
        "name": "Westin Mumbai Garden City",
        "brand": "Westin",
        "city": "Mumbai",
        "latitude": 19.1448,
        "longitude": 72.8557,
        "description": "Wellness-focused hotel in Goregaon with the signature Heavenly Bed and rejuvenating spa.",
        "semantic_text": "Wellness-oriented Westin property in Mumbai's growing western suburbs. Signature Heavenly Beds for restorative sleep, superfood-infused dining menus, outdoor heated pool, and RunWESTIN concierge for fitness enthusiasts. Ideal for health-conscious business travelers, wellness seekers, and families wanting a balanced stay. Calm rejuvenating atmosphere focused on well-being and renewal.",
        "rating": 4.3,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True},
        "price_per_night": 12000,
        "hotel_type": "business",
    },
    {
        "name": "Sheraton Grand Mumbai",
        "brand": "Sheraton",
        "city": "Mumbai",
        "latitude": 19.1180,
        "longitude": 72.8800,
        "description": "Warm inviting hotel in Andheri East ideal for extended business stays.",
        "semantic_text": "Warm and welcoming Sheraton in Mumbai's bustling Andheri East commercial district. Comfortable spacious rooms, all-day dining with international cuisine, rooftop pool, and friendly attentive service. Great for extended business stays, layovers near the airport, and family leisure trips. Relaxed unpretentious atmosphere with reliable comfort and genuine Indian hospitality.",
        "rating": 4.2,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True},
        "price_per_night": 10000,
        "hotel_type": "business",
    },
    {
        "name": "Courtyard by Marriott Mumbai International Airport",
        "brand": "Courtyard by Marriott",
        "city": "Mumbai",
        "latitude": 19.1025,
        "longitude": 72.8705,
        "description": "Efficient comfortable hotel steps from Chhatrapati Shivaji International Airport.",
        "semantic_text": "Convenient Courtyard by Marriott located minutes from Mumbai International Airport terminals. Clean modern rooms with soundproof windows, reliable high-speed wifi, 24-hour market pantry, and hearty breakfast buffet starting at 5 AM for early flights. Perfect for transit passengers, short business trips, and overnight layovers. Efficient no-fuss atmosphere focused on practicality and comfort at good value.",
        "rating": 4.1,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True},
        "price_per_night": 8000,
        "hotel_type": "business",
    },
    {
        "name": "Fairfield by Marriott Mumbai",
        "brand": "Fairfield by Marriott",
        "city": "Mumbai",
        "latitude": 19.1040,
        "longitude": 72.8750,
        "description": "Smart budget-friendly hotel near the airport with essential amenities.",
        "semantic_text": "Clean comfortable budget-friendly Fairfield near Mumbai airport offering excellent value for money. Bright modern rooms, complimentary wifi, hot breakfast included, and friendly helpful staff. Ideal for budget-conscious business travelers, solo tourists, and short stopovers. Simple efficient atmosphere delivering the essentials done well without unnecessary frills.",
        "rating": 3.9,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True},
        "price_per_night": 5000,
        "hotel_type": "budget",
    },
    # ========== DELHI (8) ==========
    {
        "name": "JW Marriott New Delhi Aerocity",
        "brand": "JW Marriott",
        "city": "Delhi",
        "latitude": 28.5530,
        "longitude": 77.1175,
        "description": "Luxurious urban retreat in Aerocity with stunning contemporary design and world-class dining.",
        "semantic_text": "Premium JW Marriott in Delhi's vibrant Aerocity hospitality district near the airport. Stunning contemporary architecture, luxurious spa with Ayurvedic treatments, temperature-controlled pool, and five exceptional dining venues. Perfect for luxury business stays, romantic city breaks, and destination weddings. Sophisticated elegant atmosphere combining modern luxury with traditional Indian warmth.",
        "rating": 4.7,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "wedding_venue": True},
        "price_per_night": 18000,
        "hotel_type": "luxury",
    },
    {
        "name": "The Ritz-Carlton New Delhi",
        "brand": "The Ritz-Carlton",
        "city": "Delhi",
        "latitude": 28.5880,
        "longitude": 77.2140,
        "description": "Ultra-premium luxury hotel near Connaught Place blending Indian heritage with contemporary elegance.",
        "semantic_text": "Exquisite Ritz-Carlton experience in Delhi's prestigious diplomatic enclave near Connaught Place. Opulent rooms with handcrafted Indian textiles, legendary Ritz-Carlton spa, infinity pool overlooking the city, and curated fine dining experiences. Ideal for heads of state, luxury connoisseurs, and once-in-a-lifetime celebrations. Regal sophisticated atmosphere with unparalleled personalized service and timeless Indian grandeur.",
        "rating": 4.9,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "butler_service": True, "limousine": True},
        "price_per_night": 35000,
        "hotel_type": "luxury",
    },
    {
        "name": "Sheraton New Delhi",
        "brand": "Sheraton",
        "city": "Delhi",
        "latitude": 28.5930,
        "longitude": 77.1750,
        "description": "Established business hotel near Delhi's diplomatic and government quarter.",
        "semantic_text": "Well-established Sheraton in Delhi's leafy diplomatic enclave, popular with embassy officials and government visitors. Spacious rooms with work desks, excellent multi-cuisine restaurant, outdoor pool surrounded by gardens, and comprehensive business center. Great for government delegations, diplomatic travelers, and business meetings. Dignified professional atmosphere with quiet garden surroundings and reliable service.",
        "rating": 4.3,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "business_center": True},
        "price_per_night": 11000,
        "hotel_type": "business",
    },
    {
        "name": "Westin Delhi NCR",
        "brand": "Westin",
        "city": "Delhi",
        "latitude": 28.5230,
        "longitude": 77.2050,
        "description": "Modern wellness-focused hotel in South Delhi with easy metro access.",
        "semantic_text": "Contemporary Westin property in South Delhi's up-and-coming business district with easy metro connectivity. Wellness-centric experience with signature Heavenly Bed, nutritious Eat Well menu, jogging trail maps, and rejuvenating spa treatments. Ideal for health-conscious travelers, young professionals on work trips, and families exploring Delhi. Fresh vibrant atmosphere focused on balance, energy, and modern comfort.",
        "rating": 4.2,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True},
        "price_per_night": 9500,
        "hotel_type": "business",
    },
    {
        "name": "Renaissance Delhi City Centre",
        "brand": "Renaissance",
        "city": "Delhi",
        "latitude": 28.6275,
        "longitude": 77.2180,
        "description": "Vibrant city-center hotel near Karol Bagh blending local culture with modern style.",
        "semantic_text": "Stylish Renaissance property in the heart of Delhi near Karol Bagh market, immersing guests in the city's vibrant culture. Rooftop bar with Red Fort views, locally inspired restaurant celebrating Delhi street food heritage, and modern art-filled lobby. Perfect for culture-seeking travelers, foodies, and those wanting to experience authentic Delhi. Energetic lively atmosphere connecting guests to the pulse of India's capital.",
        "rating": 4.4,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True},
        "price_per_night": 13000,
        "hotel_type": "luxury",
    },
    {
        "name": "Marriott Delhi Aerocity",
        "brand": "Marriott Hotels",
        "city": "Delhi",
        "latitude": 28.5560,
        "longitude": 77.1120,
        "description": "Solid business-class hotel in Aerocity with excellent airport proximity.",
        "semantic_text": "Reliable upscale Marriott in Delhi Aerocity offering seamless airport convenience with business-class comfort. Modern rooms with dedicated workspace, 24-hour gym, refreshing outdoor pool, and multiple dining options including a bakery cafe. Ideal for business travelers, transit passengers wanting more than an airport hotel, and short family stays. Professional efficient atmosphere with Marriott's consistent quality standards.",
        "rating": 4.3,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True},
        "price_per_night": 12000,
        "hotel_type": "business",
    },
    {
        "name": "Courtyard by Marriott Delhi NCR",
        "brand": "Courtyard by Marriott",
        "city": "Delhi",
        "latitude": 28.5370,
        "longitude": 77.2850,
        "description": "Comfortable mid-range hotel in Noida sector for business and leisure travelers.",
        "semantic_text": "Comfortable Courtyard property in the fast-developing Noida corridor of Delhi NCR. Clean modern rooms, reliable wifi, hearty buffet breakfast, 24/7 market pantry, and a casual restaurant serving pan-Asian and Indian favorites. Perfect for IT sector business travelers, visiting families, and weekend staycations. Practical comfortable atmosphere with good value in a growing commercial hub.",
        "rating": 4.0,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True},
        "price_per_night": 7500,
        "hotel_type": "business",
    },
    {
        "name": "Fairfield by Marriott Delhi Airport",
        "brand": "Fairfield by Marriott",
        "city": "Delhi",
        "latitude": 28.5500,
        "longitude": 77.1200,
        "description": "Smart value hotel near Delhi airport for no-fuss travelers.",
        "semantic_text": "Clean efficient Fairfield by Marriott near Delhi International Airport offering straightforward great-value accommodation. Bright functional rooms, complimentary buffet breakfast, fast free wifi, and friendly front desk service. Ideal for budget-conscious transit travelers, early morning flight catch-ups, and solo explorers. Simple fresh atmosphere with genuine warmth, delivering a comfortable stay at an honest price.",
        "rating": 3.8,
        "amenities": {"wifi": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True},
        "price_per_night": 4500,
        "hotel_type": "budget",
    },
    # ========== AGRA (5) ==========
    {
        "name": "Courtyard by Marriott Agra",
        "brand": "Courtyard by Marriott",
        "city": "Agra",
        "latitude": 27.1610,
        "longitude": 78.0510,
        "description": "Comfortable mid-range hotel just 2km from the Taj Mahal with heritage-inspired interiors.",
        "semantic_text": "Courtyard by Marriott located 2km from Taj Mahal, Agra. Quiet peaceful mid-range property with heritage-inspired Mughal architecture details, comfortable rooms with work desks, business center, reliable high-speed wifi, and clean comfortable rooms. Ideal for solo travelers and couples on a heritage tour, history enthusiasts, and budget-conscious tourists wanting proximity to the Taj. Charming relaxed atmosphere with excellent value breakfast.",
        "rating": 4.2,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "travel_desk": True},
        "price_per_night": 6000,
        "hotel_type": "budget",
    },
    {
        "name": "Fairfield by Marriott Agra",
        "brand": "Fairfield by Marriott",
        "city": "Agra",
        "latitude": 27.1550,
        "longitude": 78.0550,
        "description": "Budget-friendly hotel near the Taj Mahal with essential comforts and warm hospitality.",
        "semantic_text": "Simple comfortable Fairfield by Marriott within 3km of the magnificent Taj Mahal in Agra. Clean functional rooms, complimentary breakfast with Indian and continental options, friendly local staff with great sightseeing tips, and reliable wifi. Perfect for backpackers upgrading from hostels, budget couples, and heritage tour groups. Unpretentious homely atmosphere providing a clean restful base for exploring Agra's wonders.",
        "rating": 3.9,
        "amenities": {"wifi": True, "breakfast": True, "parking": True, "restaurant": True, "travel_desk": True},
        "price_per_night": 3500,
        "hotel_type": "budget",
    },
    {
        "name": "JW Marriott Agra",
        "brand": "JW Marriott",
        "city": "Agra",
        "latitude": 27.1680,
        "longitude": 78.0480,
        "description": "Premium luxury hotel with breathtaking Taj Mahal views from rooftop infinity pool.",
        "semantic_text": "Luxurious JW Marriott in Agra offering spectacular Taj Mahal views from rooftop infinity pool, premium suites, and fine dining restaurant. World-class spa with traditional Ayurvedic treatments, elegant Mughal-inspired architecture, and impeccable butler service. Perfect for romantic getaways, luxury heritage travel, honeymoons, and photographers seeking the perfect Taj sunrise. Breathtaking serene atmosphere combining architectural grandeur with the romance of India's most iconic monument.",
        "rating": 4.8,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "taj_view": True},
        "price_per_night": 25000,
        "hotel_type": "luxury",
    },
    {
        "name": "Sheraton Agra",
        "brand": "Sheraton",
        "city": "Agra",
        "latitude": 27.1700,
        "longitude": 78.0350,
        "description": "Warm inviting hotel with easy Taj Mahal access and family-friendly amenities.",
        "semantic_text": "Welcoming Sheraton property in Agra offering comfortable family-friendly accommodation with easy access to the Taj Mahal and Agra Fort. Spacious family rooms, kids splash pool, multi-cuisine restaurant with special children's menu, and cultural evening performances showcasing local arts. Ideal for families visiting the Taj, school heritage trips, and multi-generational vacations. Warm lively atmosphere with genuine hospitality and thoughtful touches for guests of all ages.",
        "rating": 4.1,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "kids_club": True},
        "price_per_night": 9000,
        "hotel_type": "business",
    },
    {
        "name": "Renaissance Agra",
        "brand": "Renaissance",
        "city": "Agra",
        "latitude": 27.1730,
        "longitude": 78.0450,
        "description": "Boutique-style hotel near the Taj Mahal celebrating Agra's artisan heritage with contemporary flair.",
        "semantic_text": "Boutique-style Renaissance celebrating Agra's rich artisan heritage near the Taj Mahal. Locally crafted marble inlay decor, rooftop restaurant with monument views, artisan workshop experiences in the lobby, and stylish contemporary rooms with traditional accents. Perfect for culturally curious travelers, art and craft enthusiasts, and couples seeking a distinctive Agra experience. Creative immersive atmosphere connecting guests with Agra's living craft traditions and the timeless beauty of Mughal architecture.",
        "rating": 4.3,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "artisan_shop": True},
        "price_per_night": 11000,
        "hotel_type": "luxury",
    },
    # ========== GOA (8) ==========
    {
        "name": "JW Marriott Goa",
        "brand": "JW Marriott",
        "city": "Goa",
        "latitude": 15.5149,
        "longitude": 73.7680,
        "description": "Stunning beachfront resort in Candolim with serene ocean views and world-class spa.",
        "semantic_text": "Luxurious JW Marriott resort in Goa with serene ocean views, premium spa, and rooftop infinity pool overlooking the Arabian Sea. Perfect for romantic getaways, honeymoons, high-end workcations, and destination celebrations. Private beach access, award-winning breakfast buffet with Goan specialties, and an adults-preferred ambiance wing with a peaceful unhurried atmosphere. Tropical palm-fringed setting blending Goan charm with Marriott's finest luxury.",
        "rating": 4.8,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "beach_access": True, "private_beach": True},
        "price_per_night": 28000,
        "hotel_type": "resort",
    },
    {
        "name": "W Goa",
        "brand": "W Hotels",
        "city": "Goa",
        "latitude": 15.5432,
        "longitude": 73.7575,
        "description": "Trendy vibrant beachfront lifestyle hotel on Vagator Beach with electric nightlife.",
        "semantic_text": "Electric vibrant W Goa perched dramatically on the cliffs of Vagator Beach with sweeping ocean views. High-energy beachfront lifestyle hotel with legendary sunset DJ sessions, chic contemporary design, FIT gym, and glamorous pool scene. Perfect for young trendsetting travelers, bachelor parties, fashion-forward couples, and nightlife enthusiasts. Bold energetic party atmosphere with Goa's most happening beach bar, vibrant social spaces, and stunning clifftop sunset views.",
        "rating": 4.5,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "beach_access": True, "dj": True},
        "price_per_night": 22000,
        "hotel_type": "resort",
    },
    {
        "name": "Marriott Resort & Spa Goa",
        "brand": "Marriott Hotels",
        "city": "Goa",
        "latitude": 15.3800,
        "longitude": 73.8350,
        "description": "Tranquil beachfront resort in South Goa with pristine Miramar Beach access.",
        "semantic_text": "Peaceful Marriott Resort nestled along the pristine quieter shores of South Goa's Miramar Beach. Secluded beachfront with gentle lapping waves, sprawling tropical gardens, Ayurvedic spa pavilion, and outdoor yoga deck at sunrise. Excellent for wellness retreats, quiet romantic escapes, meditation-focused workcations, and nature lovers. Deeply tranquil healing atmosphere away from Goa's party circuit, offering genuine rest, rejuvenation, and connection with nature.",
        "rating": 4.6,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "beach_access": True, "yoga_deck": True},
        "price_per_night": 20000,
        "hotel_type": "resort",
    },
    {
        "name": "Westin Goa",
        "brand": "Westin",
        "city": "Goa",
        "latitude": 15.5015,
        "longitude": 73.7720,
        "description": "Wellness-focused beach resort in Calangute with holistic health programs.",
        "semantic_text": "Wellness-oriented Westin resort on Calangute Beach in Goa offering a holistic health-focused beach vacation. Farm-to-table dining at the Eat Well restaurant, daily yoga and meditation sessions, RunWESTIN beach trail, signature Heavenly Spa treatments, and nutritious superfood smoothies at the pool bar. Perfect for health-conscious travelers, yoga retreats, active families, and anyone seeking a balanced rejuvenating Goa holiday. Refreshing wholesome atmosphere nurturing body and mind in a beautiful beachfront setting.",
        "rating": 4.4,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "beach_access": True, "yoga_deck": True},
        "price_per_night": 16000,
        "hotel_type": "resort",
    },
    {
        "name": "Sheraton Goa Resort",
        "brand": "Sheraton",
        "city": "Goa",
        "latitude": 15.5260,
        "longitude": 73.7650,
        "description": "Family-friendly beachfront resort in Candolim with extensive kids activities.",
        "semantic_text": "Warm family-friendly Sheraton beachfront resort in bustling Candolim, Goa. Dedicated kids club with supervised activities, family pool with waterslides, spacious connecting family rooms, and a beachfront restaurant with kid-friendly menu. Evening Goan cultural shows, cooking classes, and family beach games. Perfect for family beach holidays, school vacation trips, and multi-generational Goa getaways. Lively welcoming atmosphere designed around family fun and creating cherished holiday memories together.",
        "rating": 4.3,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "beach_access": True, "kids_club": True, "waterslides": True},
        "price_per_night": 12000,
        "hotel_type": "resort",
    },
    {
        "name": "Renaissance Goa Resort",
        "brand": "Renaissance",
        "city": "Goa",
        "latitude": 15.3460,
        "longitude": 73.9520,
        "description": "Boutique resort in South Goa's serene Palolem with Portuguese-Goan heritage charm.",
        "semantic_text": "Boutique Renaissance resort nestled in the serene beauty of South Goa's Palolem Beach. Intimate Portuguese-Goan heritage architecture with terracotta roofs, lush tropical gardens, infinity pool overlooking paddy fields, and a farm-to-table restaurant celebrating Goan-Portuguese fusion cuisine. Ideal for honeymooners, couples celebrating anniversaries, artists seeking inspiration, and those preferring South Goa's laid-back rhythm. Intimate romantic atmosphere surrounded by coconut groves, bird song, and the gentle sound of the Arabian Sea.",
        "rating": 4.5,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "beach_access": True},
        "price_per_night": 17000,
        "hotel_type": "resort",
    },
    {
        "name": "Fairfield by Marriott Goa Benaulim",
        "brand": "Fairfield by Marriott",
        "city": "Goa",
        "latitude": 15.2680,
        "longitude": 73.9300,
        "description": "Budget-friendly beachside hotel in South Goa's serene Benaulim area.",
        "semantic_text": "Simple comfortable Fairfield by Marriott in sleepy Benaulim, South Goa, offering excellent budget beachside value. Clean airy rooms with balcony views, complimentary breakfast with local Goan breads, bicycle rentals for exploring quiet village roads, and just 200m walk to a pristine uncrowded beach. Perfect for budget beach lovers, backpacker couples, long-stay digital nomads, and those who prefer South Goa's slow quiet charm. Laid-back simple atmosphere surrounded by coconut trees, paddy fields, and the authentic Goan countryside.",
        "rating": 3.9,
        "amenities": {"wifi": True, "pool": True, "breakfast": True, "parking": True, "restaurant": True, "bicycle_rental": True},
        "price_per_night": 4000,
        "hotel_type": "budget",
    },
    {
        "name": "Courtyard by Marriott Goa Colva",
        "brand": "Courtyard by Marriott",
        "city": "Goa",
        "latitude": 15.2800,
        "longitude": 73.9200,
        "description": "Comfortable mid-range beach hotel in Colva with modern amenities and local charm.",
        "semantic_text": "Comfortable Courtyard by Marriott near Colva Beach in South Goa offering reliable mid-range beachside accommodation. Modern rooms with garden or pool views, a casual all-day restaurant serving Goan seafood specialties, outdoor pool surrounded by frangipani trees, and friendly local staff. Great for couples seeking a relaxed Goan beach holiday, small friend groups, and retirees escaping the winter. Unhurried pleasant atmosphere with the authentic rhythm of South Goa's fishing villages nearby.",
        "rating": 4.0,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True},
        "price_per_night": 7000,
        "hotel_type": "resort",
    },
    # ========== BANGALORE (7) ==========
    {
        "name": "JW Marriott Bengaluru",
        "brand": "JW Marriott",
        "city": "Bangalore",
        "latitude": 12.9724,
        "longitude": 77.5970,
        "description": "Distinguished luxury hotel in the heart of Bangalore with exceptional dining and events.",
        "semantic_text": "Elegant JW Marriott in the heart of Bangalore's central business district, a landmark of refined luxury. Soaring atrium lobby, multiple award-winning restaurants including a pan-Asian rooftop venue, temperature-controlled outdoor pool, and the serene Spa by JW. Perfect for C-suite business travelers, luxury-seeking tech leaders, and grand wedding celebrations. Sophisticated cosmopolitan atmosphere reflecting Bangalore's status as India's innovation capital with genuine South Indian warmth.",
        "rating": 4.7,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "business_center": True},
        "price_per_night": 20000,
        "hotel_type": "luxury",
    },
    {
        "name": "The Ritz-Carlton Bangalore",
        "brand": "The Ritz-Carlton",
        "city": "Bangalore",
        "latitude": 12.9685,
        "longitude": 77.5985,
        "description": "Ultra-luxurious address in central Bangalore with legendary personalized service.",
        "semantic_text": "Ultra-luxurious Ritz-Carlton in Bangalore's vibrant central district setting the city's gold standard for luxury hospitality. Exquisite rooms with handpicked Indian art, legendary Ritz-Carlton Club Lounge experience, world-class spa sanctuary, and a stunning rooftop infinity pool. Exceptional fine dining venues perfect for power dinners. Ideal for visiting CEOs, luxury travelers, and landmark celebrations. Majestic sophisticated atmosphere with the impeccable personalized service that defines the Ritz-Carlton legacy.",
        "rating": 4.9,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "butler_service": True, "club_lounge": True},
        "price_per_night": 32000,
        "hotel_type": "luxury",
    },
    {
        "name": "Marriott Bengaluru Whitefield",
        "brand": "Marriott Hotels",
        "city": "Bangalore",
        "latitude": 12.9675,
        "longitude": 77.7500,
        "description": "Prime business hotel in Bangalore's tech corridor with extensive conference facilities.",
        "semantic_text": "Strategic Marriott property in Whitefield, Bangalore's thriving IT corridor, home to major tech parks and multinational offices. Comprehensive business facilities, multiple meeting rooms with video conferencing, executive lounge, 24-hour business center, and express valet service. Excellent restaurant and bar for client entertainment. Perfect for tech sector business travelers, visiting consultants, and corporate training events. Professional efficient atmosphere designed for the productivity-focused IT professional.",
        "rating": 4.4,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "business_center": True, "conference_rooms": True},
        "price_per_night": 14000,
        "hotel_type": "business",
    },
    {
        "name": "Sheraton Grand Bangalore",
        "brand": "Sheraton",
        "city": "Bangalore",
        "latitude": 12.9718,
        "longitude": 77.6420,
        "description": "Warm business hotel in Indiranagar with great connectivity to tech parks and dining.",
        "semantic_text": "Warm welcoming Sheraton Grand in Bangalore's lively Indiranagar neighborhood, surrounded by the city's best restaurants, craft breweries, and boutiques. Comfortable spacious rooms with dedicated workspaces, excellent all-day dining, a lively lobby bar popular with the tech crowd, and a rooftop pool. Great for startup founders, tech professionals, and business travelers who appreciate being in a vibrant neighborhood rather than an isolated business district. Energetic sociable atmosphere blending business efficiency with Bangalore's famous startup culture.",
        "rating": 4.3,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "business_center": True},
        "price_per_night": 12000,
        "hotel_type": "business",
    },
    {
        "name": "Westin Bangalore",
        "brand": "Westin",
        "city": "Bangalore",
        "latitude": 12.9400,
        "longitude": 77.6300,
        "description": "Wellness-focused hotel in Koramangala near Bangalore's startup ecosystem.",
        "semantic_text": "Contemporary Westin in Koramangala, Bangalore's buzzing startup and youth hub, focusing on wellness for the always-on tech crowd. Ergonomic workstations in every room, nutritious brain-food menus, 24-hour WestinWORKOUT fitness studio, and relaxation pods in the lobby for power naps between meetings. Excellent for startup founders burning the midnight oil, tech professionals on extended stays, and health-conscious digital nomads. Energetic modern atmosphere balancing the intensity of startup life with genuine wellness and self-care.",
        "rating": 4.2,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True},
        "price_per_night": 10000,
        "hotel_type": "business",
    },
    {
        "name": "Courtyard by Marriott Bangalore Outer Ring Road",
        "brand": "Courtyard by Marriott",
        "city": "Bangalore",
        "latitude": 12.9530,
        "longitude": 77.6850,
        "description": "Efficient business hotel on Bangalore's tech corridor with great value.",
        "semantic_text": "Efficient Courtyard by Marriott on Bangalore's Outer Ring Road IT corridor, home to major global tech companies. Clean modern rooms with reliable wifi and ergonomic work areas, 24-hour grab-and-go pantry, hearty breakfast buffet from early hours for pre-meeting fuel, and a casual restaurant with craft beers on tap. Ideal for visiting software engineers, IT project teams, and budget-conscious tech business travelers. Practical productive atmosphere focused on what matters: good connectivity, good food, and good rest.",
        "rating": 4.0,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "business_center": True},
        "price_per_night": 7000,
        "hotel_type": "business",
    },
    {
        "name": "Fairfield by Marriott Bangalore",
        "brand": "Fairfield by Marriott",
        "city": "Bangalore",
        "latitude": 12.9650,
        "longitude": 77.6950,
        "description": "Budget-friendly smart hotel for business travelers in India's Silicon Valley.",
        "semantic_text": "Smart budget-friendly Fairfield by Marriott in Bangalore's bustling tech corridor offering excellent value for IT business travelers. Bright compact rooms with fast wifi, complimentary hot breakfast, friendly efficient service, and easy access to major tech parks. Perfect for young software professionals, visiting interns, and solo business travelers watching their per-diem. Simple fresh atmosphere delivering the essentials: clean room, strong wifi, hot breakfast, and a genuine smile from the team.",
        "rating": 3.9,
        "amenities": {"wifi": True, "breakfast": True, "parking": True, "restaurant": True},
        "price_per_night": 4500,
        "hotel_type": "budget",
    },
    # ========== JAIPUR (5) ==========
    {
        "name": "JW Marriott Jaipur Resort & Spa",
        "brand": "JW Marriott",
        "city": "Jaipur",
        "latitude": 26.9050,
        "longitude": 75.7950,
        "description": "Majestic Rajasthani palace-style luxury resort with stunning Aravalli hill views.",
        "semantic_text": "Magnificent JW Marriott palace-style resort in Jaipur inspired by Rajasthan's royal architecture, set against the backdrop of the ancient Aravalli hills. Grand courtyards with fountains, world-class Rajasthani spa rituals, palatial outdoor pool, and regal dining in an ornate durbar hall. Perfect for luxury heritage travelers, destination weddings, royal honeymoons, and those seeking an authentic palace experience. Majestic romantic atmosphere transporting guests to the grandeur of Rajasthan's maharaja era with modern luxury seamlessly woven in.",
        "rating": 4.8,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "heritage_tours": True, "wedding_venue": True},
        "price_per_night": 30000,
        "hotel_type": "luxury",
    },
    {
        "name": "Renaissance Jaipur",
        "brand": "Renaissance",
        "city": "Jaipur",
        "latitude": 26.9150,
        "longitude": 75.7800,
        "description": "Art-inspired hotel celebrating Jaipur's craft heritage with contemporary Rajasthani design.",
        "semantic_text": "Vibrant art-inspired Renaissance in the Pink City of Jaipur celebrating Rajasthan's rich craft traditions. Block-printed textiles in every room, a lobby gallery showcasing local artisans, rooftop restaurant with Amber Fort views, and craft workshop experiences curated by local master artisans. Ideal for culturally curious travelers, textile and craft enthusiasts, photographers, and creative professionals seeking inspiration. Colorful creative atmosphere deeply connected to Jaipur's living heritage of blue pottery, block printing, and gemstone artistry.",
        "rating": 4.4,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "artisan_workshops": True},
        "price_per_night": 15000,
        "hotel_type": "luxury",
    },
    {
        "name": "Marriott Jaipur",
        "brand": "Marriott Hotels",
        "city": "Jaipur",
        "latitude": 26.9080,
        "longitude": 75.7730,
        "description": "Contemporary business-leisure hotel near Jaipur's commercial district with heritage touches.",
        "semantic_text": "Modern Marriott property in Jaipur blending business efficiency with Rajasthani heritage charm. Comfortable contemporary rooms with traditional block-print accents, a multi-cuisine restaurant with a spectacular Rajasthani thali, outdoor pool with cabana seating, and easy access to both the commercial district and heritage sites. Perfect for business travelers who want to explore Jaipur's forts and bazaars on weekends, MICE events, and family city breaks. Efficient warm atmosphere bridging Jaipur's royal past and its modern aspirations.",
        "rating": 4.3,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "business_center": True},
        "price_per_night": 11000,
        "hotel_type": "business",
    },
    {
        "name": "Courtyard by Marriott Jaipur",
        "brand": "Courtyard by Marriott",
        "city": "Jaipur",
        "latitude": 26.9200,
        "longitude": 75.7900,
        "description": "Comfortable mid-range hotel with easy access to Jaipur's heritage sites and bazaars.",
        "semantic_text": "Comfortable Courtyard by Marriott in Jaipur providing a reliable mid-range base for exploring the Pink City. Clean modern rooms with air conditioning (essential after a day in the desert heat), rooftop pool with city views, hearty breakfast buffet with Rajasthani specialties, and a helpful travel desk for heritage sightseeing. Great for heritage tourists, small group travelers, and families exploring Jaipur, Amber Fort, and Hawa Mahal. Practical comfortable atmosphere offering a cool refreshing retreat after dusty days of sightseeing.",
        "rating": 4.1,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "travel_desk": True},
        "price_per_night": 6500,
        "hotel_type": "business",
    },
    {
        "name": "Fairfield by Marriott Jaipur",
        "brand": "Fairfield by Marriott",
        "city": "Jaipur",
        "latitude": 26.9130,
        "longitude": 75.7850,
        "description": "Smart value hotel near Jaipur railway station for travelers exploring Rajasthan.",
        "semantic_text": "Clean efficient Fairfield by Marriott near Jaipur railway station offering great value for Rajasthan explorers. Bright functional rooms, complimentary breakfast with fresh parathas, reliable wifi for planning the next day's itinerary, and friendly staff with excellent local recommendations. Perfect for backpackers treating themselves, budget couples on a Rajasthan circuit, and solo travelers seeking a clean reliable base. Simple welcoming atmosphere providing comfort and safety for travelers discovering the wonders of the Pink City on a budget.",
        "rating": 3.8,
        "amenities": {"wifi": True, "breakfast": True, "restaurant": True, "travel_desk": True},
        "price_per_night": 3500,
        "hotel_type": "budget",
    },
    # ========== DUBAI (8) ==========
    {
        "name": "JW Marriott Marquis Dubai",
        "brand": "JW Marriott Marquis",
        "city": "Dubai",
        "latitude": 25.1850,
        "longitude": 55.2580,
        "description": "Iconic twin-tower luxury hotel in Business Bay, one of the world's tallest hotels.",
        "semantic_text": "Iconic JW Marriott Marquis Dubai, one of the world's tallest hotels, dominating the Business Bay skyline. Spectacular panoramic views from floor-to-ceiling windows, award-winning international dining collection, luxurious Saray Spa, and a stunning outdoor pool deck overlooking Dubai Water Canal. Perfect for luxury business travelers, grand celebrations, and discerning tourists wanting Dubai at its most impressive. Towering sophisticated atmosphere epitomizing Dubai's ambition, scale, and uncompromising luxury standards.",
        "rating": 4.7,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "business_center": True, "concierge": True},
        "price_per_night": 35000,
        "hotel_type": "luxury",
    },
    {
        "name": "The Ritz-Carlton Dubai",
        "brand": "The Ritz-Carlton",
        "city": "Dubai",
        "latitude": 25.0850,
        "longitude": 55.1450,
        "description": "Mediterranean-style beachfront resort on JBR Walk with private beach and lush gardens.",
        "semantic_text": "Magnificent Ritz-Carlton beachfront resort on Dubai's prestigious JBR Walk, styled like a Mediterranean palace with lush gardens cascading to a pristine private beach. Legendary Ritz-Carlton service, six swimming pools, world-class spa in a standalone Arabian villa, and exceptional dining from beachfront seafood to afternoon tea in the grand lobby. Ideal for luxury family beach holidays, romantic anniversaries, and travelers seeking Dubai's finest beachfront experience. Refined serene atmosphere offering a peaceful garden oasis amid Dubai's dazzling skyline.",
        "rating": 4.9,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "private_beach": True, "butler_service": True, "kids_club": True},
        "price_per_night": 55000,
        "hotel_type": "resort",
    },
    {
        "name": "W Dubai Mina Seyahi",
        "brand": "W Hotels",
        "city": "Dubai",
        "latitude": 25.0950,
        "longitude": 55.1400,
        "description": "Bold vibrant beachfront lifestyle hotel on Jumeirah Beach with electric social scene.",
        "semantic_text": "Electrifying W Dubai Mina Seyahi on Jumeirah Beach, a bold vibrant lifestyle destination with a legendary beachfront party scene. Cutting-edge design by world-famous architects, glamorous adults-only pool scene with international DJs, FIT gym with personal trainers, and chic dining concepts. Perfect for young trendsetters, fashion-forward travelers, music lovers, and Dubai weekenders seeking the hottest beach club energy. Bold glamorous party atmosphere with Dubai's most stylish crowd, epic sunset sessions, and non-stop social energy.",
        "rating": 4.5,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "beach_access": True, "dj": True, "beach_club": True},
        "price_per_night": 30000,
        "hotel_type": "resort",
    },
    {
        "name": "Sheraton Dubai Mall of the Emirates",
        "brand": "Sheraton",
        "city": "Dubai",
        "latitude": 25.1170,
        "longitude": 55.2010,
        "description": "Connected to Mall of the Emirates, perfect for shoppers and families.",
        "semantic_text": "Convenient Sheraton directly connected to Mall of the Emirates, Dubai's premier shopping destination with indoor ski slope and endless retail therapy. Comfortable family-friendly rooms, direct mall access for climate-controlled convenience, multiple dining options from quick bites to international buffet, and a heated outdoor pool with city views. Ideal for shopping enthusiasts, families combining retail with leisure, and transit visitors wanting a comfortable base. Bustling convenient atmosphere offering seamless access to one of Dubai's best malls.",
        "rating": 4.2,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "mall_access": True},
        "price_per_night": 18000,
        "hotel_type": "business",
    },
    {
        "name": "Marriott Dubai Palm Jumeirah",
        "brand": "Marriott Hotels",
        "city": "Dubai",
        "latitude": 25.1380,
        "longitude": 55.1170,
        "description": "Beachfront resort on iconic Palm Jumeirah with stunning Arabian Gulf views.",
        "semantic_text": "Stunning Marriott beachfront resort on Dubai's iconic Palm Jumeirah island with breathtaking Arabian Gulf views. Contemporary Arabian design, private beach with calm turquoise waters, beachfront restaurant serving Middle Eastern seafood, infinity pool blending into the Gulf horizon, and easy access to Atlantis Aquaventure waterpark. Excellent for families wanting the full Palm Jumeirah experience, couples on a romantic beach holiday, and sun-seekers. Relaxed resort atmosphere with the unique thrill of staying on one of the world's most famous man-made islands.",
        "rating": 4.4,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "private_beach": True, "water_sports": True},
        "price_per_night": 28000,
        "hotel_type": "resort",
    },
    {
        "name": "Renaissance Dubai Downtown",
        "brand": "Renaissance",
        "city": "Dubai",
        "latitude": 25.1920,
        "longitude": 55.2750,
        "description": "Stylish downtown hotel with Burj Khalifa views and Dubai Mall proximity.",
        "semantic_text": "Stylish Renaissance in the heart of Downtown Dubai with mesmerizing Burj Khalifa and Dubai Fountain views. Contemporary art-filled interiors, rooftop pool with skyline panorama, vibrant restaurant celebrating Middle Eastern street food with a modern twist, and walking distance to Dubai Mall and the Opera. Perfect for culture and art lovers, couples celebrating special occasions, and first-time Dubai visitors wanting to be at the center of everything. Cosmopolitan energetic atmosphere right in the beating heart of modern Dubai with the world's tallest tower as your neighbor.",
        "rating": 4.4,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "burj_khalifa_view": True},
        "price_per_night": 22000,
        "hotel_type": "luxury",
    },
    {
        "name": "Courtyard by Marriott Dubai Green Community",
        "brand": "Courtyard by Marriott",
        "city": "Dubai",
        "latitude": 25.0150,
        "longitude": 55.2250,
        "description": "Peaceful garden-set hotel in Dubai's Green Community, away from city bustle.",
        "semantic_text": "Quiet peaceful Courtyard by Marriott nestled in Dubai's leafy Green Community, a refreshing escape from the city's high-energy pace. Surrounded by landscaped gardens and walking trails, outdoor pool in a tranquil courtyard, restaurant with al fresco garden dining, and a relaxed family-friendly vibe. Perfect for business travelers preferring a quieter setting, families wanting garden space, and long-stay guests seeking a calm residential neighborhood. Serene laid-back atmosphere offering a rare slice of tranquility in dynamic Dubai.",
        "rating": 4.1,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "garden": True},
        "price_per_night": 10000,
        "hotel_type": "business",
    },
    {
        "name": "Fairfield by Marriott Dubai Airport",
        "brand": "Fairfield by Marriott",
        "city": "Dubai",
        "latitude": 25.2500,
        "longitude": 55.3500,
        "description": "Smart budget hotel near Dubai International Airport for transit travelers.",
        "semantic_text": "Efficient Fairfield by Marriott near Dubai International Airport terminals offering smart budget-friendly accommodation. Clean compact rooms with excellent soundproofing, 24-hour complimentary coffee station, grab-and-go breakfast for early departures, and frequent complimentary airport shuttle. Ideal for transit passengers with long layovers, airline crew on rest stops, and budget-conscious travelers needing a practical Dubai base. Simple efficient atmosphere focused on smooth arrivals and departures with genuine warmth.",
        "rating": 3.9,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True},
        "price_per_night": 6000,
        "hotel_type": "budget",
    },
    # ========== SINGAPORE (7) ==========
    {
        "name": "JW Marriott Singapore South Beach",
        "brand": "JW Marriott",
        "city": "Singapore",
        "latitude": 1.2950,
        "longitude": 103.8565,
        "description": "Architectural luxury hotel near Marina Bay blending heritage with futuristic design.",
        "semantic_text": "Stunning architectural JW Marriott in Singapore's vibrant City Hall district, a masterpiece blending conserved heritage buildings with futuristic Philippe Starck design. Flowing indoor-outdoor spaces, rooftop infinity pool with Marina Bay skyline views, world-class Japanese and international dining, and an ultra-modern spa. Perfect for luxury city breaks, design and architecture enthusiasts, romantic celebrations, and business leaders. Sophisticated cutting-edge atmosphere embodying Singapore's unique blend of heritage, innovation, and tropical luxury.",
        "rating": 4.7,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "rooftop_pool": True},
        "price_per_night": 38000,
        "hotel_type": "luxury",
    },
    {
        "name": "The Ritz-Carlton Millenia Singapore",
        "brand": "The Ritz-Carlton",
        "city": "Singapore",
        "latitude": 1.2910,
        "longitude": 103.8600,
        "description": "Legendary Marina Bay luxury with iconic 8-window bathroom views and art collection.",
        "semantic_text": "Legendary Ritz-Carlton Millenia on Marina Bay, home to one of Southeast Asia's finest contemporary art collections and the famous 8-window octagonal bathroom views. Unparalleled Marina Bay panorama from every room, a 4,200-piece museum-worthy art collection throughout the hotel, award-winning Cantonese fine dining, and a lavish 25-meter outdoor pool. The gold standard for luxury in Singapore. Perfect for art connoisseurs, luxury travelers, milestone celebrations, and those who appreciate the finest things in life.",
        "rating": 4.9,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "art_collection": True, "butler_service": True, "marina_bay_view": True},
        "price_per_night": 55000,
        "hotel_type": "luxury",
    },
    {
        "name": "W Singapore Sentosa Cove",
        "brand": "W Hotels",
        "city": "Singapore",
        "latitude": 1.2500,
        "longitude": 103.8350,
        "description": "Vibrant waterfront lifestyle hotel on Sentosa Island with marina views and pool parties.",
        "semantic_text": "Electric vibrant W Singapore at Sentosa Cove, a glamorous waterfront lifestyle playground on Singapore's resort island. The city's hottest weekend pool parties, cutting-edge design with tropical flair, 24-hour FIT gym, Whatever/Whenever concierge service, and chic marina-side dining. Perfect for young professionals, fashion-forward staycationers, yacht enthusiasts, and those seeking Singapore's best weekend vibe. Bold energetic atmosphere with stunning marina sunsets, tropical cocktails, and Singapore's most stylish crowd.",
        "rating": 4.5,
        "amenities": {"wifi": True, "spa": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "marina_view": True},
        "price_per_night": 32000,
        "hotel_type": "resort",
    },
    {
        "name": "Marriott Singapore Tang Plaza",
        "brand": "Marriott Hotels",
        "city": "Singapore",
        "latitude": 1.3050,
        "longitude": 103.8325,
        "description": "Iconic Orchard Road hotel atop Tang Plaza with unbeatable shopping access.",
        "semantic_text": "Iconic Marriott perched atop Tang Plaza on Orchard Road, Singapore's legendary shopping boulevard. Direct access to the city's best retail therapy, an outdoor pool oasis amid the Orchard Road energy, excellent Cantonese restaurant frequented by locals, and warm Singaporean hospitality. Perfect for shopping enthusiasts, foodie travelers exploring Singapore's hawker culture, and business travelers wanting a central connected base. Vibrant convenient atmosphere placing guests at the epicenter of Singapore's shopping, dining, and entertainment.",
        "rating": 4.3,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True, "bar": True, "shopping_access": True},
        "price_per_night": 25000,
        "hotel_type": "business",
    },
    {
        "name": "Sheraton Towers Singapore",
        "brand": "Sheraton",
        "city": "Singapore",
        "latitude": 1.3110,
        "longitude": 103.8300,
        "description": "Established business hotel on Scotts Road with warm service and lush gardens.",
        "semantic_text": "Well-established Sheraton Towers on Scotts Road, a peaceful garden-accented business hotel in the heart of Singapore. Lush waterfall feature in the lobby, tranquil outdoor pool surrounded by tropical greenery, excellent Cantonese restaurant renowned for dim sum, and warm personalized service that brings guests back for decades. Ideal for repeat business travelers to Singapore, conference attendees, and travelers seeking a calm garden refuge near Orchard Road. Serene established atmosphere with old-world hospitality and beautifully maintained tropical gardens.",
        "rating": 4.2,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "business_center": True, "garden": True},
        "price_per_night": 20000,
        "hotel_type": "business",
    },
    {
        "name": "Courtyard by Marriott Singapore Novena",
        "brand": "Courtyard by Marriott",
        "city": "Singapore",
        "latitude": 1.3200,
        "longitude": 103.8450,
        "description": "Modern mid-range hotel in Novena medical and business district with great MRT access.",
        "semantic_text": "Modern comfortable Courtyard by Marriott in Singapore's Novena district, well-connected to the city center by MRT. Bright functional rooms with city views, a rooftop pool, casual all-day dining with Peranakan flavors, and proximity to major medical centers and corporate offices. Perfect for medical tourism visitors, business travelers to Novena's corporate hub, and budget-savvy tourists wanting good value in pricey Singapore. Practical efficient atmosphere with excellent transport links and reliable comfort at a fair Singapore price.",
        "rating": 4.1,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True},
        "price_per_night": 15000,
        "hotel_type": "business",
    },
    {
        "name": "Fairfield by Marriott Singapore",
        "brand": "Fairfield by Marriott",
        "city": "Singapore",
        "latitude": 1.3150,
        "longitude": 103.8550,
        "description": "Clean affordable hotel near city center for budget-conscious Singapore visitors.",
        "semantic_text": "Clean simple Fairfield by Marriott in Singapore offering rare affordable comfort in one of Asia's priciest cities. Compact efficient rooms, complimentary breakfast, excellent MRT connectivity to downtown, and friendly local staff with great hawker center recommendations. Ideal for budget travelers who refuse hostels, young couples on a Singapore stopover, and solo explorers. Simple fresh atmosphere providing a clean safe comfortable base for exploring the Lion City without breaking the bank.",
        "rating": 3.9,
        "amenities": {"wifi": True, "breakfast": True, "restaurant": True},
        "price_per_night": 9000,
        "hotel_type": "budget",
    },
    # ========== LONDON (7) ==========
    {
        "name": "JW Marriott Grosvenor House London",
        "brand": "JW Marriott",
        "city": "London",
        "latitude": 51.5100,
        "longitude": -0.1550,
        "description": "Historic landmark hotel on Park Lane with Mayfair elegance and iconic Great Room.",
        "semantic_text": "Historic JW Marriott Grosvenor House on Park Lane, a London landmark since 1929 exuding timeless Mayfair elegance. The iconic Great Room has hosted royalty and Hollywood legends, afternoon tea remains a cherished tradition, the Park Room overlooks Hyde Park, and the service is quintessentially British. Perfect for luxury heritage travelers, romantic London weekends, afternoon tea connoisseurs, and those celebrating life's most special moments. Grand storied atmosphere steeped in London's aristocratic history with modern luxury thoughtfully integrated.",
        "rating": 4.7,
        "amenities": {"wifi": True, "spa": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "afternoon_tea": True, "concierge": True},
        "price_per_night": 45000,
        "hotel_type": "luxury",
    },
    {
        "name": "The Ritz-Carlton London",
        "brand": "The Ritz-Carlton",
        "city": "London",
        "latitude": 51.5070,
        "longitude": -0.1420,
        "description": "Ultra-luxurious Mayfair hotel blending British aristocratic tradition with modern refinement.",
        "semantic_text": "Exquisite Ritz-Carlton in the heart of Mayfair, London's most prestigious district, offering an ultra-luxurious experience rooted in British aristocratic tradition. Bespoke suites with handcrafted furnishings, legendary Ritz-Carlton butler service, Michelin-starred dining, and a world-class spa sanctuary hidden beneath the London streets. Walking distance to Buckingham Palace, Bond Street, and the Royal Parks. Perfect for royalty-level service seekers, luxury connoisseurs, and defining life moments. Refined regal atmosphere epitomizing the pinnacle of London luxury hospitality.",
        "rating": 4.9,
        "amenities": {"wifi": True, "spa": True, "gym": True, "breakfast": True, "parking": True, "restaurant": True, "bar": True, "butler_service": True, "michelin_restaurant": True, "concierge": True},
        "price_per_night": 65000,
        "hotel_type": "luxury",
    },
    {
        "name": "W London Leicester Square",
        "brand": "W Hotels",
        "city": "London",
        "latitude": 51.5105,
        "longitude": -0.1300,
        "description": "Electric lifestyle hotel in Soho at Leicester Square, heart of London's entertainment.",
        "semantic_text": "Electric vibrant W London perched above Leicester Square, the thrumming heart of London's theatre and entertainment district. Bold design inspired by Soho's creative energy, glamorous cocktail bar that transforms into a late-night hotspot, 24-hour Whatever/Whenever service, and rooms with floor-to-ceiling neon-lit views over London's most famous square. Perfect for theatre-goers, nightlife enthusiasts, fashion insiders, and media professionals. High-energy glamorous atmosphere placing guests center-stage in London's most exhilarating neighborhood.",
        "rating": 4.5,
        "amenities": {"wifi": True, "spa": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True, "nightclub": True},
        "price_per_night": 38000,
        "hotel_type": "luxury",
    },
    {
        "name": "Marriott London County Hall",
        "brand": "Marriott Hotels",
        "city": "London",
        "latitude": 51.5010,
        "longitude": -0.1190,
        "description": "Historic County Hall hotel on the South Bank with Big Ben and Thames views.",
        "semantic_text": "Magnificent Marriott in the historic County Hall building on London's South Bank with postcard-perfect views of Big Ben, the Houses of Parliament, and the Thames. Grand historic architecture, a stunning indoor pool in the original council chamber, riverside dining terrace, and unbeatable location for London sightseeing with the London Eye next door. Perfect for family sightseeing holidays, romantic London proposals, history enthusiasts, and first-time London visitors. Historic awe-inspiring atmosphere with views of London's most iconic landmarks from your window.",
        "rating": 4.5,
        "amenities": {"wifi": True, "pool": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True, "thames_view": True, "concierge": True},
        "price_per_night": 35000,
        "hotel_type": "luxury",
    },
    {
        "name": "Sheraton Grand London Park Lane",
        "brand": "Sheraton",
        "city": "London",
        "latitude": 51.5050,
        "longitude": -0.1470,
        "description": "Art Deco landmark on Piccadilly with Green Park views and refined club atmosphere.",
        "semantic_text": "Elegant Art Deco Sheraton Grand on Piccadilly overlooking Green Park, a refined London landmark since 1927. Beautifully restored Palm Court lounge with afternoon tea, clubby bar with leather armchairs, spacious rooms with park views, and a discreet private members club atmosphere. Ideal for business leaders, diplomatic travelers, antique shoppers on nearby Jermyn Street, and those who appreciate Art Deco architecture. Refined gentlemanly atmosphere evoking a more gracious era of London travel with impeccable modern service.",
        "rating": 4.4,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True, "afternoon_tea": True, "concierge": True},
        "price_per_night": 32000,
        "hotel_type": "luxury",
    },
    {
        "name": "Courtyard by Marriott London City",
        "brand": "Courtyard by Marriott",
        "city": "London",
        "latitude": 51.5180,
        "longitude": -0.0870,
        "description": "Modern business hotel near Liverpool Street in London's financial district.",
        "semantic_text": "Modern efficient Courtyard by Marriott in the City of London financial district near Liverpool Street Station. Contemporary rooms with work desks, 24-hour market, casual restaurant, and easy access to both the Square Mile's corporate headquarters and Shoreditch's creative energy. Perfect for financial sector business travelers, conference attendees at nearby venues, and weekend city-breakers wanting a central well-connected base. Professional efficient atmosphere in the heart of London's financial center at reasonable City rates.",
        "rating": 4.1,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True, "business_center": True},
        "price_per_night": 18000,
        "hotel_type": "business",
    },
    {
        "name": "Fairfield by Marriott London Heathrow",
        "brand": "Fairfield by Marriott",
        "city": "London",
        "latitude": 51.4700,
        "longitude": -0.4500,
        "description": "Smart budget airport hotel near Heathrow for early flights and transit stays.",
        "semantic_text": "Clean efficient Fairfield by Marriott near London Heathrow Airport offering excellent budget value for airport-adjacent stays. Soundproofed rooms for peaceful sleep despite airport proximity, 24-hour tea and coffee station, grab-and-go breakfast for early departures from 4 AM, and frequent affordable Hoppa bus service to all terminals. Perfect for early morning flight catch-ups, transit passengers, and budget-conscious travelers to London. Simple practical atmosphere delivering a clean comfortable pre-flight stay without Heathrow's usual premium pricing.",
        "rating": 3.8,
        "amenities": {"wifi": True, "breakfast": True, "parking": True, "airport_shuttle": True, "restaurant": True},
        "price_per_night": 7000,
        "hotel_type": "budget",
    },
    # ========== NEW YORK (7) ==========
    {
        "name": "JW Marriott Essex House New York",
        "brand": "JW Marriott",
        "city": "New York",
        "latitude": 40.7680,
        "longitude": -73.9795,
        "description": "Iconic Art Deco landmark on Central Park South with stunning park views.",
        "semantic_text": "Historic JW Marriott Essex House, an iconic Art Deco landmark on Central Park South with magnificent views of Central Park's treetops and skyline. Grand 1930s architecture with beautifully restored interiors, the lobby's stunning original murals, a refined South Gate restaurant overlooking the park, and the most coveted address for New York's fall foliage and holiday seasons. Perfect for luxury travelers seeking authentic old New York glamour, romantic Central Park proposals, and holiday-season magic. Timeless elegant atmosphere evoking Manhattan's golden age with breathtaking park panoramas.",
        "rating": 4.7,
        "amenities": {"wifi": True, "spa": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True, "central_park_view": True, "concierge": True},
        "price_per_night": 50000,
        "hotel_type": "luxury",
    },
    {
        "name": "The Ritz-Carlton New York Central Park",
        "brand": "The Ritz-Carlton",
        "city": "New York",
        "latitude": 40.7650,
        "longitude": -73.9760,
        "description": "Quintessential Manhattan luxury on Central Park South with legendary service.",
        "semantic_text": "Quintessential Ritz-Carlton on Central Park South, the ultimate expression of Manhattan luxury and legendary service. Gracious rooms and suites with Central Park views, the famed Ritz-Carlton Club Lounge with dedicated concierge, La Prairie spa with curated wellness journeys, and a level of intuitive personalized service that anticipates every need. Steps from Fifth Avenue shopping, Lincoln Center, and Museum Mile. Perfect for luxury connoisseurs, Fifth Avenue shoppers, cultural patrons, and those who settle only for the very best. Refined exclusive atmosphere delivering the definitive New York luxury hotel experience.",
        "rating": 4.9,
        "amenities": {"wifi": True, "spa": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True, "butler_service": True, "club_lounge": True, "central_park_view": True, "concierge": True, "la_prairie_spa": True},
        "price_per_night": 75000,
        "hotel_type": "luxury",
    },
    {
        "name": "W New York Times Square",
        "brand": "W Hotels",
        "city": "New York",
        "latitude": 40.7605,
        "longitude": -73.9850,
        "description": "Electric lifestyle hotel in Times Square with dazzling neon views and rooftop lounge.",
        "semantic_text": "Electric vibrant W New York perched above Times Square with dazzling neon-lit views of the world's most famous intersection. Bold cutting-edge design, a rooftop lounge with jaw-dropping Broadway panoramas, 24-hour Whatever/Whenever concierge, and the city's energy pulsing right outside the door. Perfect for Broadway theatre-goers, first-time New York visitors wanting the full Times Square experience, and nightlife lovers staying in the city that never sleeps. High-voltage exhilarating atmosphere at the very epicenter of New York's electric energy.",
        "rating": 4.4,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True, "rooftop_bar": True, "times_square_view": True, "concierge": True},
        "price_per_night": 32000,
        "hotel_type": "luxury",
    },
    {
        "name": "Marriott Marquis New York",
        "brand": "Marriott Marquis",
        "city": "New York",
        "latitude": 40.7590,
        "longitude": -73.9865,
        "description": "Landmark Times Square hotel with iconic rooftop revolving restaurant and Broadway location.",
        "semantic_text": "Landmark Marriott Marquis in Times Square, one of New York's most famous hotels, home to the iconic revolving rooftop restaurant and lounge with 360-degree Manhattan views. The heart of the Broadway theatre district, massive atrium lobby soaring 45 stories, and direct pedestrian bridge access to the best Broadway shows. Perfect for theatre lovers booking a Broadway weekend, families on a classic New York holiday, and convention attendees. Grand theatrical atmosphere celebrating the spectacle and excitement of Times Square and Broadway.",
        "rating": 4.4,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True, "revolving_restaurant": True, "broadway_access": True, "business_center": True},
        "price_per_night": 28000,
        "hotel_type": "business",
    },
    {
        "name": "Sheraton New York Times Square",
        "brand": "Sheraton",
        "city": "New York",
        "latitude": 40.7620,
        "longitude": -73.9840,
        "description": "Massive well-located business hotel near Times Square and Midtown offices.",
        "semantic_text": "Sprawling Sheraton New York in Midtown Manhattan, one of the city's largest hotels, ideally located near Times Square and the Midtown corporate corridor. Extensive meeting and convention facilities, a lively lobby bar that's a favorite after-work spot, comfortable rooms with city views, and walking distance to Rockefeller Center and Broadway. Excellent for business travelers to Midtown offices, conference attendees, and groups needing a central Manhattan base. Busy professional atmosphere in a hotel that keeps Manhattan's business engine running smoothly.",
        "rating": 4.1,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True, "business_center": True, "conference_rooms": True},
        "price_per_night": 22000,
        "hotel_type": "business",
    },
    {
        "name": "Courtyard by Marriott New York Manhattan/Central Park",
        "brand": "Courtyard by Marriott",
        "city": "New York",
        "latitude": 40.7665,
        "longitude": -73.9810,
        "description": "Smart comfortable hotel steps from Central Park at reasonable Manhattan rates.",
        "semantic_text": "Smart comfortable Courtyard by Marriott just steps from Central Park in Midtown Manhattan offering excellent value in one of the world's most expensive hotel markets. Modern functional rooms (a rarity in older New York hotels), 24-hour market, and the priceless advantage of Central Park as your morning jogging route. Perfect for budget-savvy Manhattan tourists, park lovers, and business travelers who prioritize location and value over opulence. Practical efficient atmosphere providing a clean comfortable Manhattan base at a fair price in an unbeatable location.",
        "rating": 4.1,
        "amenities": {"wifi": True, "gym": True, "breakfast": True, "restaurant": True, "bar": True},
        "price_per_night": 18000,
        "hotel_type": "business",
    },
    {
        "name": "Fairfield by Marriott New York Manhattan/Times Square",
        "brand": "Fairfield by Marriott",
        "city": "New York",
        "latitude": 40.7580,
        "longitude": -73.9930,
        "description": "Budget-friendly Manhattan hotel near Times Square for value-seeking NYC explorers.",
        "semantic_text": "Clean simple Fairfield by Marriott in Manhattan near Times Square, a rare budget-friendly option in the heart of New York City. Compact efficient rooms, complimentary breakfast (a real money-saver in NYC), free wifi, and walking distance to Times Square, Hudson Yards, and the High Line. Ideal for budget travelers who want Manhattan convenience without Manhattan prices, student groups, and solo explorers spending their budget on experiences not rooms. Simple practical atmosphere providing a clean comfortable crash pad in the middle of the greatest city on earth.",
        "rating": 3.8,
        "amenities": {"wifi": True, "breakfast": True, "restaurant": True},
        "price_per_night": 10000,
        "hotel_type": "budget",
    },
]
